# -*- coding: utf-8 -*-
"""example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXBiBuU9mEZLkz_lj1o7uD3UxazUWvF9
"""

print("Hello world"
a = 10