# -*- coding: utf-8 -*-
"""syntax_checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXBiBuU9mEZLkz_lj1o7uD3UxazUWvF9
"""

def check_syntax(file_path):
    try:
        # Read the file content
        with open(file_path, "r") as f:
            code = f.read()

        # Try compiling (checks syntax only, does not run code)
        compile(code, file_path, 'exec')

        print("✅ No Syntax Errors Found")

    except SyntaxError as e:
        print(f"❌ Syntax Error at line {e.lineno}: {e.msg}")
    except Exception as e:
        print(f"⚠️ Other Error: {str(e)}")

if __name__ == "__main__":
    # Example test files
    print("Checking example.py:")
    check_syntax("example.py")

    print("\nChecking correct.py:")
    check_syntax("correct.py")